# Generated by Django 3.0.6 on 2020-05-24 16:55

import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('miembro', '0010_auto_20200523_2225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='miembro',
            name='email_personal',
        ),
        migrations.AlterField(
            model_name='miembro',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Correo electrónico personal'),
        ),
        migrations.AlterField(
            model_name='miembro',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='Nombres'),
        ),
        migrations.AlterField(
            model_name='miembro',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Apellidos'),
        ),
        migrations.AlterField(
            model_name='miembro',
            name='rol_miembro',
            field=models.ForeignKey(help_text='Rol del miembro dentro de la rama', null=True, on_delete=django.db.models.deletion.PROTECT, to='miembro.Rol_miembro', verbose_name='Rol miembro'),
        ),
        migrations.AlterField(
            model_name='miembro',
            name='username',
            field=models.CharField(error_messages={'unique': 'Un usuario con este correo electrónico ya existe.'}, max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='Correo electrónico institucional'),
        ),
    ]
